---
# At which level should you no longer be able to receive kits?
Maximum-Level: 3

# Specify a percentage of the chance that you will lose many levels.
# Default = 0.60
Chance: 0.60

# Set the default game mode.
# Default = 2
gamemode: 2

# Activate or deactivate if you want to get your old level kit back after a rejoin
save-level: false

# Set the PvP radius in which PvP should be allowed.
pvp-radius: 10

# Allow other items to be added. You can manage them in "level.yml" under "other-items".
use-other-items: false

# Here you can change the chat and nametag format.
format:
  chat: "§8[§c{level}§8] §7{player} §8> §f{msg}"
  nametag: "§8[§c{level}§8] §7{player}"

events:
  load:
    login: true
    join: true
    quit: true
    break: true
    place: true
    damage: true
    death: true
    drop: true
    hunger: true
    inv-move: true
    move: true
    respawn: true
    chat: true
    fight: true

# Here you can change the messages.
# {player} = The player is you
# {level} = Your current level
# {msg} = Your message
# {killer} = Who killed you
messages:
  join: "{player} has entered the GunGame server."
  quit: "{player} has left the GunGame server."
  death: "{player} died!"
  kill: "{player} was killed by {killer}."
  reload: "Your levels were reset by a server reload."
...